export const cards = [
  {
    id: "swsh7-215",
    name: "Umbreon VMAX",
    set: "Evolving Skies",
    number: "215 / 203",
    finish: "Illustration alternative",
    effect: "rare rainbow alt",
    type: "darkness",
    subtypes: "vmax single strike",
    image: "./assets/cards/swsh7-215.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh7/215/high.webp",
    tagline: "Un peu plus près de la lune.",
    description:
      "Umbreon tend la patte vers la lune dans l’une des illustrations les plus marquantes d’Evolving Skies.",
  },
  {
    id: "swsh8-271",
    name: "Gengar VMAX",
    set: "Fusion Strike",
    number: "271 / 264",
    finish: "Illustration alternative",
    effect: "rare rainbow alt",
    type: "darkness",
    subtypes: "vmax single strike",
    image: "./assets/cards/swsh8-271.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh8/271/high.webp",
    tagline: "Un monde délicieusement étrange.",
    description:
      "Entrez dans l’univers haut en couleur de Gengar, sublimé par des reflets arc-en-ciel.",
  },
  {
    id: "swsh4-188",
    name: "Pikachu VMAX",
    set: "Vivid Voltage",
    number: "188 / 185",
    finish: "Arc-en-ciel",
    effect: "rare rainbow",
    type: "lightning",
    subtypes: "vmax",
    image: "./assets/cards/swsh4-188.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh4/188/high.webp",
    tagline: "Une personnalité haute en couleur.",
    description:
      "Toute l’énergie de Pikachu dans sa forme VMAX, avec une délicate finition arc-en-ciel.",
  },
  {
    id: "pgo-11",
    name: "Radiant Charizard",
    set: "Pokémon GO",
    number: "011 / 078",
    finish: "Radieuse",
    effect: "radiant rare",
    type: "fire",
    subtypes: "basic radiant",
    image: "./assets/cards/pgo-11.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh10.5/011/high.webp",
    tagline: "Une flamme intemporelle.",
    description:
      "Un Charizard chromatique dont les reflets quadrillés se révèlent à chaque inclinaison.",
  },
  {
    id: "swsh8-270",
    name: "Espeon VMAX",
    set: "Fusion Strike",
    number: "270 / 264",
    finish: "Illustration alternative",
    effect: "rare rainbow alt",
    type: "psychic",
    subtypes: "vmax",
    image: "./assets/cards/swsh8-270.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh8/270/high.webp",
    tagline: "Une sieste hors du commun.",
    description:
      "Espeon s’assoupit sur les toits dans une illustration onirique qui occupe toute la carte.",
  },
  {
    id: "swsh8-250",
    name: "Mew V",
    set: "Fusion Strike",
    number: "250 / 264",
    finish: "Illustration intégrale",
    effect: "rare ultra",
    type: "psychic",
    subtypes: "basic v fusion strike",
    image: "./assets/cards/swsh8-250.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh8/250/high.webp",
    tagline: "Petit Pokémon. Grande énergie.",
    description:
      "Un Mew sur fond rose éclatant, traversé par une fine texture holographique.",
  },
  {
    id: "swsh8-245",
    name: "Celebi V",
    set: "Fusion Strike",
    number: "245 / 264",
    finish: "Illustration alternative",
    effect: "rare ultra",
    type: "grass",
    subtypes: "basic v",
    image: "./assets/cards/swsh8-245.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh8/245/high.webp",
    tagline: "Un instant suspendu.",
    description:
      "Celebi flotte au cœur de la forêt, dans une illustration aux reflets délicats.",
  },
  {
    id: "swsh7-110",
    name: "Rayquaza V",
    set: "Evolving Skies",
    number: "110 / 203",
    finish: "Holographique V",
    effect: "rare holo v",
    type: "dragon",
    subtypes: "basic v rapid strike",
    image: "./assets/cards/swsh7-110.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh7/110/high.webp",
    tagline: "Le gardien du ciel.",
    description:
      "La carte V de Rayquaza associe des couleurs profondes à de larges bandes de lumière.",
  },
];
