export const cards = [
  {
    id: "swsh7-215",
    name: "Umbreon VMAX",
    set: "Evolving Skies",
    number: "215 / 203",
    finish: "Alternate art",
    effect: "rare rainbow alt",
    type: "darkness",
    subtypes: "vmax single strike",
    image: "./assets/cards/swsh7-215.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh7/215/high.webp",
    tagline: "A little closer to the moon.",
    description:
      "Umbreon reaches for the moon in one of Evolving Skies’ most memorable illustrations.",
  },
  {
    id: "swsh8-271",
    name: "Gengar VMAX",
    set: "Fusion Strike",
    number: "271 / 264",
    finish: "Alternate art",
    effect: "rare rainbow alt",
    type: "darkness",
    subtypes: "vmax single strike",
    image: "./assets/cards/swsh8-271.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh8/271/high.webp",
    tagline: "A wonderfully strange world.",
    description:
      "Step into Gengar’s vivid alternate-art world, with a rainbow finish that catches the light.",
  },
  {
    id: "swsh4-188",
    name: "Pikachu VMAX",
    set: "Vivid Voltage",
    number: "188 / 185",
    finish: "Rainbow rare",
    effect: "rare rainbow",
    type: "lightning",
    subtypes: "vmax",
    image: "./assets/cards/swsh4-188.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh4/188/high.webp",
    tagline: "A full spectrum of personality.",
    description:
      "Pikachu’s larger-than-life VMAX form, finished in a soft wash of rainbow foil.",
  },
  {
    id: "pgo-11",
    name: "Radiant Charizard",
    set: "Pokémon GO",
    number: "011 / 078",
    finish: "Radiant",
    effect: "radiant rare",
    type: "fire",
    subtypes: "basic radiant",
    image: "./assets/cards/pgo-11.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh10.5/011/high.webp",
    tagline: "The original fire starter.",
    description:
      "A shiny Charizard with a distinctive crosshatch foil that moves as you tilt.",
  },
  {
    id: "swsh8-270",
    name: "Espeon VMAX",
    set: "Fusion Strike",
    number: "270 / 264",
    finish: "Alternate art",
    effect: "rare rainbow alt",
    type: "psychic",
    subtypes: "vmax",
    image: "./assets/cards/swsh8-270.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh8/270/high.webp",
    tagline: "A very different kind of catnap.",
    description:
      "Espeon takes a rooftop rest in this dreamy, full-bleed illustration.",
  },
  {
    id: "swsh8-250",
    name: "Mew V",
    set: "Fusion Strike",
    number: "250 / 264",
    finish: "Full art",
    effect: "rare ultra",
    type: "psychic",
    subtypes: "basic v fusion strike",
    image: "./assets/cards/swsh8-250.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh8/250/high.webp",
    tagline: "Small Pokémon. Big energy.",
    description:
      "A bright pink full-art Mew with a fine, shifting holographic texture.",
  },
  {
    id: "swsh8-245",
    name: "Celebi V",
    set: "Fusion Strike",
    number: "245 / 264",
    finish: "Alternate art",
    effect: "rare ultra",
    type: "grass",
    subtypes: "basic v",
    image: "./assets/cards/swsh8-245.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh8/245/high.webp",
    tagline: "A moment out of time.",
    description:
      "Celebi drifts through a forest scene, with delicate light across the full artwork.",
  },
  {
    id: "swsh7-110",
    name: "Rayquaza V",
    set: "Evolving Skies",
    number: "110 / 203",
    finish: "Holo V",
    effect: "rare holo v",
    type: "dragon",
    subtypes: "basic v rapid strike",
    image: "./assets/cards/swsh7-110.webp",
    source: "https://assets.tcgdex.net/en/swsh/swsh7/110/high.webp",
    tagline: "Meet the sky’s guardian.",
    description:
      "Rayquaza’s dramatic V card pairs deep color with sweeping bands of light.",
  },
];
